server:
  port: 9200
spring:
  application:
    name: ms-consumer-order
eureka:
  instance:
    prefer-ip-address: true
    hostname: ms-consumer-order
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
#actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign hystrix config
feign:
  hystrix:
    enabled: true