server:
  port: 9100
spring:
  application:
    name: ms-consumer-movie
eureka:
  instance:
    prefer-ip-address: true
    hostname: ms-consumer-movie
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
#actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign hystrix config
      feign:
        hystrix:
          enabled: true