server:
  port: 9100
spring:
  application:
    name: ms-consumer-movie
  sleuth:
    web:
      enabled: true
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true
    hostname: ms-consumer-movie
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka
#actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign hystrix config
feign:
  hystrix:
    #服务降级开关
    enabled: true
  compression:
    request:
      #开启请求压缩
      enabled: true
      #压缩支持的类型
      mime-types: text/xml,application/xml,application/json
      #压缩数据大小下限
      min-request-size: 1024
    response:
      #开启响应压缩
      enabled: true
#ribbon config
ribbon:
  eager-load:
    #设置ribbon饥饿加载，防止懒加载可能造成第一次访问超时
    enabled: true
    clients: ms-provider-user
ms-provider-user:
  ribbon:
    #ribbon缓存更新周期，默认30s
    ServerListRefreshInterval: 30000
    #连接超时时间默认2000
    ConnectTimeout: 3000
    #负载均衡超时时间默认5000
    ReadTimeout: 6000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    #同一台机器重试次数(不包含首次调用)
    MaxAutoRetries: 1
    #切换实例重试次数(不包含首次调用)
    MaxAutoRetriesNextServer: 1
    #配置负载均衡策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#hystrix配置
hystrix:
  command:
    #把default改成实例就是设置具体服务配置
    default:
      execution:
        isolation:
          #设置隔离策略默认thread，此外还有semaphore
          strategy: THREAD
          thread:
            #超时时是否应中断执行操作,默认true
            interruptOnTimeout: true
            #hystrix超时设置，默认1000ms
            timeoutInMilliseconds: 15000
        timeout:
          #HystrixCommand命令执行是否设置超时(即是否启用timeoutInMilliseconds)，默认true
          enable: true
      circuitBreaker:
        #设置打开fallback功能的错误比例,默认50
        errorThresholdPercentage: 50
        #强制打开断路器，拒绝所有功能，默认false
        forceOpen: false
        #强制关闭断路器，允许所有功能，默认false
        forceClosed: false
  threadpool:
    default:
      #当为线程隔离时设置线程池核心线程数大小,默认10
      coreSize: 15
      #当为线程隔离时设置线程池最大线程数大小,默认10
      maximumSize: 15
      #当为线程隔离时设置线程池最大空闲时间,默认1分钟
      keepAliveTimeMinutes: 1
#日志
logging:
  level:
    com.crady.movie.service.UserFeignClient: debug
